### PR TITLE
Added clone derives

### PR DESCRIPTION
**Pull request by WhySoBad**
# Add clone derives
Added `Clone` trait derives to various structs across the project.

## Changes made
* Added the `Clone` trait to all structs in the `tree` module
* Added the `Clone` trait to all structs used in structs in the `tree` module

### CODE REVIEW

**Comment by andreykaere** [comment]
Hi! Why do you want to make a distinct PR for adding `Clone`? Why is this necessary for your second PR? Can't we just merge your second one (if everything is okay there, I haven't looked at that yet)?

**Comment by WhySoBad** [comment]
Hi. 
I created two separate PR's (for each "feature" one) since I thought it would be easier to review.
Since I acidentially included the changes from this commit in the other PR as well I'm totally fine with just merging the other PR.

**Comment by andreykaere** [comment]
Well, to me it's just weird to create PR just for the sake of adding `Clone`. The main reason is that it's not clear why would you one need this? If you need these clones for implementating certain features (like you did), then it's better to have this inside that PR, so it will make more sense. Hope you got what I meant :)

**Comment by WhySoBad** [comment]
Ah now I get what you meant.
Well, I want to create an application which keeps track of the state of bspwm (as you may already have guessed). When both PR's are merged I want to add a trait to the `State` struct with methods like `remove_monitor`, `add_monitor` etc.
In the specific case of the `remove_monitor` method I need to loop over all monitors and filter the vector. When I then collect the filter results I end up with a vector containing references to monitor instances rather than with a vector containing monitor instances.
This is where I need to be able to clone the structs. Just now I realized I could have just implemented the `Clone` trait in my project for the structs but in my opinion a library should provide structs which can be cloned since it's a commonly used operation.

And for why creating two pull requests:
I'm used to the workflow in which every issue receives it's own pull request. This makes it easy to track down errors in the future and when reviewing you don't want to review 5 different features all included in one pull request. Since the addition of the `Clone` trait to all structs and the addition of a `State` struct have practically nothing in common I ended up creating two pull requests.

I hope you got my point of view :)

**Comment by andreykaere** [comment]
Hi! Sorry for getting back to you so late. Yes, I share your point of view, but I think I am not gonna merge this one and just merge the one that contains valuable changes!

**Pull request closed without merging**
